const User = require('../models/User');
const Appointment = require('../models/Appointment');
const Report = require('../models/Report');
const PDFDocument = require('pdfkit');
const bcrypt = require('bcryptjs');

exports.createDoctor = async (req, res) => {
    try {
        const { name, email, password, specialization, experience, fees, phone } = req.body;

        const userExists = await User.findOne({ email });
        if (userExists) {
            return res.status(400).json({ message: 'User already exists' });
        }

        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        const doctor = await User.create({
            name,
            email,
            password: hashedPassword,
            role: 'doctor',
            specialization,
            experience,
            fees,
            phone,
            image: '' // Optional image
        });

        if (doctor) {
            res.status(201).json({
                _id: doctor._id,
                name: doctor.name,
                email: doctor.email,
                role: doctor.role
            });
        } else {
            res.status(400).json({ message: 'Invalid user data' });
        }
    } catch (error) {
        res.status(500).json({ message: 'Server Error', error: error.message });
    }
};

exports.createStaff = async (req, res) => {
    try {
        const { name, email, password, jobTitle, department, phone } = req.body;

        const userExists = await User.findOne({ email });
        if (userExists) {
            return res.status(400).json({ message: 'User already exists' });
        }

        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        const staff = await User.create({
            name,
            email,
            password: hashedPassword,
            role: 'staff',
            jobTitle,
            department,
            phone,
            image: '' 
        });

        if (staff) {
            res.status(201).json(staff);
        } else {
            res.status(400).json({ message: 'Invalid user data' });
        }
    } catch (error) {
        res.status(500).json({ message: 'Server Error', error: error.message });
    }
};

exports.getStaff = async (req, res) => {
    try {
        const staff = await User.find({ role: 'staff' });
        res.json(staff);
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.getSystemStats = async (req, res) => {
    try {
        const doctors = await User.countDocuments({ role: 'doctor' });
        const patients = await User.countDocuments({ role: 'patient' });
        const appointments = await Appointment.countDocuments({});
        const reports = await Report.countDocuments({});
        
        // Basic trend (last 7 days appointments) - simplified
        // Real implementation would use aggregation pipeline
        
        res.json({
            doctors,
            patients,
            appointments,
            reports
        });
    } catch (error) {
        res.status(500).json({ message: 'Server Error', error: error.message });
    }
};

exports.deleteDoctor = async (req, res) => {
    try {
        const { id } = req.params;
        await User.findByIdAndDelete(id);
        // clean up appointments? For now, keep them or cascade delete.
        res.json({ message: 'Doctor deleted' });
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.generatePDFReport = async (req, res) => {
    try {
        const doc = new PDFDocument();
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=system-report.pdf');

        doc.pipe(res);

        // Content
        doc.fontSize(25).text('Smart Healthcare System Report', { align: 'center' });
        doc.moveDown();
        
        const doctors = await User.countDocuments({ role: 'doctor' });
        const patients = await User.countDocuments({ role: 'patient' });
        const appointments = await Appointment.countDocuments({});
        
        doc.fontSize(16).text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();
        doc.text('System Statistics:');
        doc.fontSize(14).list([
            `Total Doctors: ${doctors}`,
            `Total Patients: ${patients}`,
            `Total Appointments: ${appointments}`
        ]);
        
        doc.moveDown();
        doc.text('Confidential Report generated by Admin System.');

        doc.end();
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};
